### PR TITLE
scroll in jupytext

### PR DESCRIPTION
**Pull request by itcarroll**

### CODE REVIEW

**Comment by eeholmes** [comment]
@itcarroll Did you figure out how to add the `scroll-output` at the notebook level?

**Comment by itcarroll** [comment]
Yes, I added the tags to the jupytext. You still need both the metadata `scrolled=true` and `tags=["scroll-output"]`. That's something that should be raised on MyST-NB. They should read the existing metadata rather than define a new tag, methinks.

**Comment by eeholmes** [comment]
Did you have to scroll through the src and add `# + scrolled=true tags=["scroll-output"] language="bash"` where needed or what there a way to apply that to all bash cells at the notebook level?

**Comment by itcarroll** [comment]
Had to do it for each cell. But I could search/replace in the text files, didn't have to use the notebook interface.

**Pull request merged**
